### ISSUE TITLE
Also mention jsDelivr CDN in the guide

### ISSUE THREAD

**Issue by plainheart** [triggerjs/trigger#22]
I remember `unpkg` CDN has a slow speed in the Chinese mainland. So I'd like to suggest also mentioning using the jsDelivr CDN in the guide. Besides the speed, it also supports fetching any public files from the GitHub repository. For example, we can get the latest built files from the default main branch through https://cdn.jsdelivr.net/gh/triggerjs/trigger/dist/bundle.js

Here is the package in the jsDelivr CDN: https://www.jsdelivr.com/package/npm/@triggerjs/trigger

**Comment by stevenlei** [comment]
Thanks for your suggestion, so I will add the `jsdelivr` setting to `package.json` also. It is a good time to upgrade to `v1.0.8` as two new features have been added:
- Range support for `tg-map`
- Added `tg-bezier`

I will update the README along with `v1.0.8`. Thank you.

**Comment by stevenlei** [comment]
Added 0e1c843d1fc079f82cfb98e22723a091c6ab46a7
